# Generated by Django 4.2.8 on 2023-12-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_library_patron'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
                ('patron', models.CharField(max_length=100)),
                ('borrowing_date', models.DateField()),
                ('return_date', models.DateTimeField()),
            ],
        ),
    ]
